### ISSUE TITLE
dbt 1.12 reports invalid `quote_columns` macro annotation

### ISSUE THREAD

**Issue by etx121** [danflippo/dbt_constraints#130]
After upgrading from dbt Core 1.11 to 1.12, dbt commands fail while parsing `dbt_constraints` 1.0.9.

## Error

```text
Compilation Error
  [WARNING]: Argument quote_columns in the yaml for macro create_constraints has an invalid type.
```

## Environment

- dbt-core 1.12.0
- dbt-postgres 1.11.0
- dbt_constraints 1.0.9
- All warnings are treated as errors with `warn_error_options.error: all`

It looks like the package declares the argument as:

```yaml
- name: quote_columns
  type: boolean
```

dbt 1.12 accepts `bool` as the macro argument type instead of `boolean`.
There also seem to be a few other macro annotation/signature warnings in the package.

For now, we have pinned dbt Core below 1.12 and dbt-postgres below 1.11. Would it be possible to update the macro annotations for dbt 1.12 compatibility?

**Comment by etx121** [comment]
Hello,

Did you have time to check that issue when upgrading to `dbt-core` 1.12.0?
I think you only need to replace `type: boolean` with `type: bool`, in this file:
[https://github.com/Snowflake-Labs/dbt_constraints/blob/205b5cfdd51349ab3f4b6db7e8e6faf5224a8e14/macros/macros.yml#L12](https://github.com/Snowflake-Labs/dbt_constraints/blob/205b5cfdd51349ab3f4b6db7e8e6faf5224a8e14/macros/macros.yml#L12)
[https://github.com/Snowflake-Labs/dbt_constraints/blob/205b5cfdd51349ab3f4b6db7e8e6faf5224a8e14/macros/macros.yml#L29](https://github.com/Snowflake-Labs/dbt_constraints/blob/205b5cfdd51349ab3f4b6db7e8e6faf5224a8e14/macros/macros.yml#L29)
