### ISSUE TITLE
snowflake__lookup_table_privileges macro namespace/dispatch error

### ISSUE THREAD

**Issue by rvloenhout** [danflippo/dbt_constraints#117]
Hi all,

We are running into a strange error that we can't seem to figure out.

## Context

We are implementing checks to ensure that models adhere to our standards. 
One of these standards is that a dataset must have at least one primary key / unique constraint applied.
We check this by looking at `INFORMATION_SCHEMA.TABLE_CONSTRAINTS`. 
These checks are done in an `on-run-end` hook at the very end.

Normally, the `dbt_constraints` package would run after this and then apply the specified PK constraints. 
However, this conflicts with our checks (the constraint would always appear as missing at check time). 
Because of this, we first call `dbt_constraints.create_constraints()` in `on-run-end` in our `dbt_project.yml`, and then run our governance checks.

## What we do

**`dbt_project.yml`**

```yaml
vars:
  dbt_constraints_enabled: true

on-run-end:
  - "{{ dbt_constraints.create_constraints() }}"
  - "{{ otherpackage.governance_checks() }}"
```

**Example model schema test**

```yaml
tests:
  - dbt_constraints.primary_key:
      column_name: PK_COLUMN
```

This worked fine in `dbt_constraints` **v0.6.3**.

## Problem after upgrading

After upgrading to `dbt_constraints` **v1.0.0**, we get a compilation error. From the error logs it looks like it is trying to resolve a macro and fails to find `snowflake__lookup_table_privileges`.

```text
Compilation Error in operation on-run-end-0 (.\dbt_project.yml)
  'snowflake__lookup_table_privileges' is undefined

  > in macro have_ownership_priv (macros/create_constraints.sql)
  > called by macro snowflake__create_primary_key (macros/snowflake__create_constraints.sql)
  > called by macro create_primary_key (macros/create_constraints.sql)
  > called by macro create_constraints_by_type (macros/create_constraints.sql)
  > called by macro create_constraints (macros/create_constraints.sql)
  > called by operation on-run-end-0 (.\dbt_project.yml)
```

We also tried adding `dbt_constraints` to the `dispatch` search order (and moving it higher up), but without success. We are not using any macros that might have the same name, nor do we believe we’re using other packages that would collide.

## Workaround / observation

If we modify the `dbt_constraints` macro in `snowflake__create_constraints.sql` to reference the macro **via the package namespace**, things work:

```sql
{%- macro snowflake__have_references_priv(table_relation, verify_permissions, lookup_cache) -%}
  {%- if verify_permissions is sameas true -%}

    {%- set table_privileges = dbt_constraints.snowflake__lookup_table_privileges(table_relation, lookup_cache) -%}
    {%- if "REFERENCES" in table_privileges or "OWNERSHIP" in table_privileges -%}
      {{ return(true) }}
    {%- else -%}
      {{ return(false) }}
    {%- endif -%}

  {%- else -%}
    {{ return(true) }}
  {%- endif -%}
{%- endmacro -%}


{%- macro snowflake__have_ownership_priv(table_relation, verify_permissions, lookup_cache) -%}
  {%- if verify_permissions is sameas true -%}

    {%- set table_privileges = dbt_constraints.snowflake__lookup_table_privileges(table_relation, lookup_cache) -%}
    {%- if "OWNERSHIP" in table_privileges -%}
      {{ return(true) }}
    {%- else -%}
      {{ return(false) }}
    {%- endif -%}

  {%- else -%}
    {{ return(true) }}
  {%- endif -%}
{%- endmacro -%}


{%- macro snowflake__lookup_table_privileges(table_relation, lookup_cache) -%}

  {%- if table_relation.database not in lookup_cache.table_privileges -%}
    {%- do log("Caching privileges for database: " ~ table_relation.database, info=false) -%}

    {%- set lookup_query -%}
      select distinct
        upper(tp.table_schema) as "table_schema",
        upper(tp.table_name) as "table_name",
        tp.privilege_type as "privilege_type"
      from {{ table_relation.database }}.information_schema.table_privileges tp
      where (is_role_in_session(tp.grantee) or is_database_role_in_session(tp.grantee))
        and tp.privilege_type in ('OWNERSHIP', 'REFERENCES')
    {%- endset -%}

    {%- set privilege_list = run_query(lookup_query) -%}
    {%- do lookup_cache.table_privileges.update({ table_relation.database: privilege_list }) -%}
```

So it seems like this is related to macro namespace resolution: when called unqualified, it fails, but when qualified as dbt_constraints.snowflake__lookup_table_privileges, it works.
We also considered forcing macro paths (but we’d rather not rely on this long term):

```yaml
macro-paths: ["macros", "dbt_packages/dbt_constraints/macros"]
```

Could somebody explain why this stopped working between dbt_constraints v0.6.3 and v1.0.0, and what the recommended approach is to ensure the correct macro resolution?
Thanks in advance!

**Comment by ogierpaulmck** [comment]
We're having the same issue
